#pragma once
#include <memory>
#include <grpcpp/grpcpp.h>
#include "kvstore.grpc.pb.h"          // generated by protoc (in generated/ dir)
#include "raft/RaftNode.hpp"
#include "storage/Engine.hpp"

/* The .proto package is `kv`; the .cpp file uses `kvproto::`  */
namespace kvproto = kv;

/** Thin wrapper that glues Raft and RocksDB to the generated gRPC service */
class KVServer final : public kv::KeyValue::Service {
public:
    KVServer(std::shared_ptr<RaftNode>        raft,
             std::shared_ptr<Engine>          kv);

    /* RPCs implemented in `src/server/KVServer.cpp` */
    grpc::Status Put(grpc::ServerContext*,
                     const kvproto::PutRequest*,
                     kvproto::PutResponse*) override;

    grpc::Status Get(grpc::ServerContext*,
                     const kvproto::GetRequest*,
                     kvproto::GetResponse*) override;

    grpc::Status GetLinearizable(grpc::ServerContext*,
                     const kvproto::GetRequest*,
                     kvproto::GetResponse*) override;

    grpc::Status GetStale(grpc::ServerContext*,
                     const kvproto::GetRequest*,
                     kvproto::GetResponse*) override;
    grpc::Status Delete(grpc::ServerContext*,
                    const kvproto::DeleteRequest*,
                    kvproto::DeleteResponse*) override;

    grpc::Status ScanRange(grpc::ServerContext*,
                      const kvproto::ScanRangeRequest*,
                      grpc::ServerWriter<kvproto::KVPair>*) override;

    grpc::Status ScanPrefix(grpc::ServerContext*,
                       const kvproto::ScanPrefixRequest*,
                       grpc::ServerWriter<kvproto::KVPair>*) override;

private:
    std::shared_ptr<RaftNode> raft_;
    std::shared_ptr<Engine>   kv_;
};