#pragma once
#include <memory>
#include <grpcpp/grpcpp.h>
#include "proto/kv.grpc.pb.h"          // generated by protoc
#include "raft/RaftNode.hpp"
#include "storage/Engine.hpp"

/* The .proto package is `kv`; the .cpp file uses `kvproto::`  */
namespace kvproto = kv;

/** Thin wrapper that glues Raft and RocksDB to the generated gRPC service */
class KVServer final : public kv::KeyValue::Service {
public:
    KVServer(std::shared_ptr<RaftNode>        raft,
             std::shared_ptr<storage::Engine> kv);

    /* RPCs implemented in `src/server/KVServer.cpp` */
    grpc::Status Put(grpc::ServerContext*,
                     const kvproto::PutRequest*,
                     kvproto::PutResponse*) override;

    grpc::Status Get(grpc::ServerContext*,
                     const kvproto::GetRequest*,
                     kvproto::GetResponse*) override;

    grpc::Status GetLinearizable(grpc::ServerContext*,
                     const kvproto::GetRequest*,
                     kvproto::GetResponse*) override;

    grpc::Status GetStale(grpc::ServerContext*,
                     const kvproto::GetRequest*,
                     kvproto::GetResponse*) override;

private:
    std::shared_ptr<RaftNode>        raft_;
    std::shared_ptr<storage::Engine> kv_;
};
