syntax = "proto3";
package kv;

service KeyValue {
  rpc Put(PutRequest) returns (PutResponse);
  rpc Get(GetRequest) returns (GetResponse);
  rpc GetLinearizable(GetRequest) returns (GetResponse);
  rpc GetStale(GetRequest) returns (GetResponse);
  rpc Delete(DeleteRequest) returns (DeleteResponse);
  rpc ScanRange(ScanRangeRequest) returns (stream KVPair);
  rpc ScanPrefix(ScanPrefixRequest) returns (stream KVPair);
}

message PutRequest {
  string key = 1;
  string value = 2;
}

message PutResponse {}

message GetRequest {
  string key = 1;
}

message GetResponse {
  string value = 1;
}

message DeleteRequest {
  string key = 1;
}

message DeleteResponse {}

message ScanRangeRequest {
  string start_key = 1;
  string end_key = 2;
}

message ScanPrefixRequest {
  string prefix = 1;
}

message KVPair {
  string key = 1;
  string value = 2;
}